services:
  toro_toro_backend:
    build: .
    depends_on:
      - db
    ports:
      - 3333:3333
    restart: always
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/app.js"
    
  
  db:
    image: postgres:16
    container_name: toro_toro_psql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toro_toro_psql
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
